export const VEHICLE_TYPES_FETCHED = 'VEHICLE_TYPES_FETCHED'
export const VEHICLE_TYPES_HAS_ERRORED = 'VEHICLE_TYPES_HAS_ERRORED'
export const VEHICLE_TYPES_IS_LOADING = 'VEHICLE_TYPES_IS_LOADING'

export const VEHICLE_TYPE_CREATED = 'VEHICLE_TYPE_CREATED'
export const VEHICLE_TYPE_UPDATED = 'VEHICLE_TYPE_UPDATED'
export const VEHICLE_TYPE_DELETED = 'VEHICLE_TYPE_DELETED'
