export const SERVICE_ITEMS_FETCHED = 'SERVICE_ITEMS_FETCHED'
export const SERVICE_ITEMS_HAS_ERRORED = 'SERVICE_ITEMS_HAS_ERRORED'
export const SERVICE_ITEMS_IS_LOADING = 'SERVICE_ITEMS_IS_LOADING'

export const SERVICE_ITEM_CREATED = 'SERVICE_ITEM_CREATED'
export const SERVICE_ITEM_UPDATED = 'SERVICE_ITEM_UPDATED'
export const SERVICE_ITEM_DELETED = 'SERVICE_ITEM_DELETED'

export const SERVICE_ITEM_INFO_FETCHED = 'SERVICE_ITEM_INFO_FETCHED'
