export const RIDES_FETCHED = 'RIDES_FETCHED'
export const RIDES_HAS_ERRORED = 'RIDES_HAS_ERRORED'
export const RIDES_IS_LOADING = 'RIDES_IS_LOADING'

export const RIDE_INFO_FETCHED = 'RIDE_INFO_FETCHED'
export const RIDE_INFO_IS_LOADING = 'RIDE_INFO_IS_LOADING'
export const RIDE_INFO_HAS_ERRORED = 'RIDE_INFO_HAS_ERRORED'

export const RIDE_CREATED = 'RIDE_CREATED'

export const RIDE_DELETED = 'RIDE_DELETED'

export const RIDE_UPDATED = 'RIDE_UPDATED'

export const RIDE_SERVICES_FETCHED = 'RIDE_SERVICES_FETCHED'
