export const ORGANIZATIONS_FETCHED = 'ORGANIZATIONS_FETCHED'
export const ORGANIZATIONS_HAS_ERRORED = 'ORGANIZATIONS_HAS_ERRORED'
export const ORGANIZATIONS_IS_LOADING = 'ORGANIZATIONS_IS_LOADING'

export const ORGANIZATION_ADDED = 'ORGANIZATION_ADDED'

export const ORGANIZATION_INFO_FETCHED = 'ORGANIZATION_INFO_FETCHED'
export const ORGANIZATION_INFO_IS_LOADING = 'ORGANIZATION_INFO_IS_LOADING'
export const ORGANIZATION_INFO_HAS_ERRORED = 'ORGANIZATION_INFO_HAS_ERRORED'

export const ORGANIZATION_DELETED = 'ORGANIZATION_DELETED'
export const ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED'
