export const VEHICLES_FETCHED = 'VEHICLES_FETCHED'
export const VEHICLES_HAS_ERRORED = 'VEHICLES_HAS_ERRORED'
export const VEHICLES_IS_LOADING = 'VEHICLES_IS_LOADING'

export const VEHICLE_INFO_FETCHED = 'VEHICLE_INFO_FETCHED'
export const VEHICLE_INFO_IS_LOADING = 'VEHICLE_INFO_IS_LOADING'
export const VEHICLE_INFO_HAS_ERRORED = 'VEHICLE_INFO_HAS_ERRORED'

export const VEHICLE_CREATED = 'VEHICLE_CREATED'

export const VEHICLE_DELETED = 'VEHICLE_DELETED'

export const VEHICLE_UPDATED = 'VEHICLE_UPDATED'
