export const RIDE_INTERVALS_FETCHED = 'RIDE_INTERVALS_FETCHED'
export const RIDE_INTERVALS_HAS_ERRORED = 'RIDE_INTERVALS_HAS_ERRORED'
export const RIDE_INTERVALS_IS_LOADING = 'RIDE_INTERVALS_IS_LOADING'
